const SSHSession=require('../../core/ssh/SSHSession');
const net=require('net');
const TelnetSession=require('../../core/telnet/TelnetSession');
const DeviceApiClient=require('./device-api-client');
const RouterOsApiTransport=require('./routeros-api-transport');
const {SnmpTransport}=require('./snmp-transport');
const {DeviceSessionManager}=require('./device-session-manager');
const {getAttemptProfiles,getProfile,isNegotiationError,parseNegotiationError}=require('../network/ssh-algorithm-profile.service');
const {PROTOCOLS}=require('./device-protocol-resolver');
const classifyError=error=>{const text=String(error?.message||error).toLowerCase();if(/too many authentication failures|temporarily blocked|authentication.*locked/.test(text))return'DEVICE_AUTH_LOCKED';if(/auth|password|permission denied|401|403/.test(text))return'DEVICE_AUTH_FAILED';if(/econnreset|connection reset|socket hang up/.test(text))return'DEVICE_CONNECTION_RESET';if(/timeout|timed out|etimedout/.test(text))return'DEVICE_CONNECTION_TIMEOUT';if(/refused/.test(text))return'DEVICE_CONNECTION_REFUSED';if(/unreachable|enotfound|ehostunreach/.test(text))return'DEVICE_HOST_UNREACHABLE';if(/certificate|tls|ssl/.test(text))return'DEVICE_TLS_FAILED';if(/parse|syntax|unexpected/.test(text))return'DEVICE_RESPONSE_INVALID';return'DEVICE_UNKNOWN_ERROR';};
const SECRET_KEY=/password|passwd|secret|token|private.?key|passphrase|community/i;
const cleanOutput=value=>String(value||'').replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g,'').replace(/\r/g,'').replace(/\b(password|passwd|secret|token|community|passphrase)\s*(?:=|:|\s)\s*[^\s,;]+/gi,'$1 [removed]').slice(0,200000);
const sanitizeOutput=value=>{if(Array.isArray(value))return value.map(sanitizeOutput);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,SECRET_KEY.test(key)?'[removed]':sanitizeOutput(item)]));return typeof value==='string'?cleanOutput(value):value;};
const routerOsRestPath=command=>{const source=String(command||'').trim();if(/^\/export\b/.test(source))throw Object.assign(new Error('RouterOS REST does not expose a safe full-export read endpoint; use RouterOS API or SSH for export.'),{code:'DEVICE_CAPABILITY_UNSUPPORTED',status:400});const tokens=source.replace(/^\//,'').split(/\s+/).filter(token=>!['print','monitor','all','once','terse'].includes(token));return`/rest/${tokens.join('/')}`;};
class DeviceConnectionService{
 constructor(prisma,adapters={}){this.prisma=prisma;this.SSHSession=adapters.SSHSession||SSHSession;this.TelnetSession=adapters.TelnetSession||TelnetSession;this.ApiClient=adapters.DeviceApiClient||DeviceApiClient;this.SnmpTransport=adapters.SnmpTransport||SnmpTransport;this.sessions=new DeviceSessionManager(prisma,{createTransport:(device,credentials,protocol)=>this.createTransport(device,credentials,protocol),onEvent:(type,data)=>this.onEvent?.(type,data)});}
 async createTransport(device,credentials,protocol){if(protocol===PROTOCOLS.SNMP)return new this.SnmpTransport(device,credentials);if([PROTOCOLS.ROUTEROS_API,PROTOCOLS.ROUTEROS_API_TLS].includes(protocol))return new RouterOsApiTransport(device,credentials,protocol);if([PROTOCOLS.ROUTEROS_REST,PROTOCOLS.VENDOR_API,PROTOCOLS.RESTCONF].includes(protocol)){const client=new this.ApiClient(device,credentials),close=client.close?.bind(client),probe=protocol===PROTOCOLS.ROUTEROS_REST?'/rest/system/resource':device.deviceType==='fortiget-firewall'?'/api/v2/monitor/system/status':'/';client.connect=async()=>{await client.get(probe,{retry:false});return client;};client.close=()=>close?.();return client;}if(![PROTOCOLS.SSH,PROTOCOLS.TELNET].includes(protocol))throw Object.assign(new Error(`${protocol} transport is not installed or configured for this device.`),{code:'DEVICE_PROTOCOL_UNSUPPORTED',status:400});const method=protocol===PROTOCOLS.TELNET?'telnet':'ssh',Session=method==='telnet'?this.TelnetSession:this.SSHSession,username=credentials[`${method}Username`]||credentials.sshUsername||credentials.telnetUsername,password=credentials[`${method}Password`]||credentials.sshPassword||credentials.telnetPassword;if(!username||(!password&&!credentials.sshPrivateKey))throw Object.assign(new Error(`Missing ${method.toUpperCase()} credentials.`),{code:'DEVICE_CREDENTIAL_MISSING',status:400});const huawei=/huawei/i.test(`${device.vendor||''} ${device.deviceType||''}`),base={host:device.host,port:device.sshPort||device.managementPort,username,password,privateKey:credentials.sshPrivateKey,passphrase:credentials.sshKeyPassphrase,enablePassword:credentials.enablePassword,vendor:device.vendor,deviceType:device.deviceType,platform:device.platform,timeout:device.connectionTimeout,commandTimeout:device.commandTimeout,keepaliveInterval:15000,keepaliveCountMax:3,tryKeyboard:huawei};if(method==='telnet'){const connection=new Session(base);return connection;}const attempts=getAttemptProfiles(device);let lastError;for(let index=0;index<attempts.length;index++){const profile=attempts[index],selected=getProfile(profile),connection=new Session({...base,profile,algorithms:selected.algorithms});try{await connection.connect();connection.profile=profile;connection.profilesAttempted=attempts.slice(0,index+1);connection.legacyCompatibilityUsed=Boolean(selected.legacy);connection.connect=async()=>connection;return connection;}catch(error){lastError=error;connection.close?.();if(index>=attempts.length-1||!isNegotiationError(error))break;}}lastError.profile=lastError.profile||attempts.at(-1);lastError.profilesAttempted=attempts;if(isNegotiationError(lastError)){lastError.negotiation=parseNegotiationError(lastError);lastError.code='SSH_ALGORITHM_NEGOTIATION_FAILED';lastError.status=502;}throw lastError;}
 async open(device,credentialOverride=null,context={}){const session=await this.sessions.getOrCreateSession({ispId:context.ispId||device.ispId,userId:context.userId||0,device,credentialOverride,requestedProtocol:context.requestedProtocol||'AUTO',socketId:context.socketId,protocolAvailability:context.protocolAvailability}),connection=session.transport;return{method:session.protocol,protocol:session.protocol,connection,session,profile:connection.profile||null,profilesAttempted:connection.profilesAttempted||[],legacyCompatibilityUsed:Boolean(connection.legacyCompatibilityUsed),diagnostics:connection.getDiagnostics?.()||null,close:()=>this.sessions.release(session,context.socketId)};}
 async probeTcp(device){const started=Date.now(),timeout=Math.max(1000,Math.min(Number(device.connectionTimeout||15000),15000));return new Promise((resolve,reject)=>{let settled=false,banner='';const socket=net.createConnection({host:device.host,port:device.managementPort});const done=error=>{if(settled)return;settled=true;socket.destroy();const sshBanner=/SSH-[\d.]+-/.test(banner);if(error&&!sshBanner)return reject(error);resolve({tcpReachable:true,banner:banner.slice(0,500)||null,latencyMs:Date.now()-started,resetAfterBanner:Boolean(error)});};socket.setTimeout(timeout);socket.once('connect',()=>setTimeout(()=>done(),350));socket.on('data',chunk=>{banner+=chunk.toString('utf8');if(/SSH-[\d.]+-/.test(banner))done();});socket.once('timeout',()=>done(Object.assign(new Error('TCP connection timed out.'),{code:'ETIMEDOUT'})));socket.once('error',done);});}
 async withConnection(device,callback,credentialOverride=null,context={}){const started=Date.now();let handle;try{handle=await this.open(device,credentialOverride,context);const result=await this.sessions.run(handle.session,()=>callback(handle.connection,handle.method));return{result,durationMs:Date.now()-started,method:handle.method,protocol:handle.protocol,sessionId:handle.session.publicSessionId,profile:handle.profile,profilesAttempted:handle.profilesAttempted,legacyCompatibilityUsed:handle.legacyCompatibilityUsed,diagnostics:handle.connection.getDiagnostics?.()||handle.diagnostics};}catch(error){error.failureType=classifyError(error);throw error;}finally{handle?.close();}}
 async execute(device,command,context={}){return this.withConnection(device,async(connection,method)=>sanitizeOutput(method===PROTOCOLS.SNMP?await connection.getModule(context.module||command):[PROTOCOLS.ROUTEROS_API,PROTOCOLS.ROUTEROS_API_TLS].includes(method)?await connection.get(command):method===PROTOCOLS.ROUTEROS_REST?await connection.get(routerOsRestPath(command)):[PROTOCOLS.VENDOR_API,PROTOCOLS.RESTCONF].includes(method)?await connection.get(command||'/'):await connection.runShellSession(send=>send(command,Math.min(2000,Math.max(500,Number(device.commandTimeout||15000)/10))))),null,context);}
 closeForDevice(deviceId,reason){this.sessions.closeForDevice(deviceId,reason);}closeAll(){this.sessions.closeAll();}
}
module.exports={DeviceConnectionService,classifyError,cleanOutput,sanitizeOutput,routerOsRestPath};
