const DEVICE_TYPES=Object.freeze({
  mikrotik:{label:'MikroTik Management',vendor:'MikroTik',defaultMethod:'web_api',modules:['dashboard','quick-set','capsman','interfaces','wireless','bridge','ppp','mesh','ip','mpls','routing','system','queues','dot1x','files','lcd','log','terminal','radius','tools','partition','support-output']},
  cisco:{label:'Cisco Management',vendor:'Cisco',defaultMethod:'ssh',modules:['dashboard','system','interfaces','vlans','stp','mac-table','arp','ip-addresses','routing','acls','nat','dhcp','users','aaa','snmp','ntp','syslog','configuration','terminal','reboot']},
  'huawei-olt':{label:'Huawei OLT Management',vendor:'Huawei',defaultMethod:'ssh',modules:['dashboard','chassis','boards','pon-ports','uplinks','onus','onu-discovery','vlans','profiles','alarms','logs','statistics','backup','terminal','reboot']},
  'nokia-bng':{label:'Nokia BNG',vendor:'Nokia',defaultMethod:'ssh',modules:['dashboard','system','chassis','cards','ports','interfaces','vlans','routing','subscribers','address-pools','aaa','radius','qos','policies','logs','alarms','statistics','backup','terminal','reboot']},
  bdcom:{label:'BD Com',vendor:'BDCOM',defaultMethod:'telnet',modules:['dashboard','chassis','boards','pon-ports','uplinks','onus','onu-discovery','vlans','profiles','alarms','logs','statistics','backup','terminal','reboot']},
  cdata:{label:'CDATA',vendor:'CDATA',defaultMethod:'telnet',modules:['dashboard','chassis','boards','pon-ports','uplinks','onus','onu-discovery','vlans','profiles','alarms','logs','statistics','backup','terminal','reboot']},
  vsol:{label:'VSOL',vendor:'VSOL',defaultMethod:'web_api',modules:['dashboard','chassis','boards','pon-ports','uplinks','onus','onu-discovery','vlans','profiles','alarms','logs','statistics','backup','terminal','reboot']},
  'nokia-olt':{label:'NOKIA OLT',vendor:'Nokia',defaultMethod:'ssh',modules:['dashboard','chassis','boards','pon-ports','uplinks','onus','onu-discovery','vlans','profiles','alarms','logs','statistics','backup','terminal','reboot']},
  'fortiget-firewall':{label:'FortiGate Firewall',vendor:'Fortinet',defaultMethod:'web_api',modules:['dashboard','health','interfaces','zones','routing','objects','policies','nat','users','authentication','vpn','certificates','ha','licenses','logs','backup','terminal','reboot']},
  'alto-palo':{label:'Alto Palo',vendor:'Palo Alto',defaultMethod:'web_api',modules:['dashboard','health','interfaces','zones','virtual-routers','routing','objects','policies','nat','users','authentication','vpn','certificates','ha','licenses','logs','backup','terminal','reboot']},
  sophos:{label:'Sophos',vendor:'Sophos',defaultMethod:'web_api',modules:['dashboard','health','interfaces','zones','routing','objects','policies','nat','users','authentication','vpn','certificates','ha','licenses','logs','backup','terminal','reboot']},
  'linux-server':{label:'Linux Server',vendor:'Linux',defaultMethod:'ssh',modules:['dashboard','system','cpu','memory','disks','filesystems','interfaces','addresses','routes','neighbors','dns','ports','processes','services','logs','users','groups','ssh','firewall','scheduled-tasks','packages','updates','terminal','reboot','shutdown']}
  ,'juniper-switch':{label:'Juniper Switch',vendor:'Juniper',defaultMethod:'ssh',modules:['dashboard','system','chassis','interfaces','vlans','ethernet-switching','stp','lldp','lacp','routing','routes','bgp','ospf','security','logs','configuration','terminal','reboot']}
  ,'juniper-bras':{label:'Juniper BRAS',vendor:'Juniper',defaultMethod:'ssh',modules:['dashboard','system','chassis','interfaces','subscribers','pppoe','dhcp','radius','address-pools','routing','routes','bgp','ospf','isis','mpls','services','qos','firewall','logs','configuration','terminal','reboot']}
});
const METHODS=['web_api','ssh','telnet'],STATUSES=['online','offline','failure','maintenance'];
const READ_ONLY=new Set(['dashboard','system','health','chassis','boards','ports','pon-ports','uplinks','onus','onu-discovery','interfaces','vlans','stp','mac-table','arp','ip-addresses','routing','subscribers','address-pools','aaa','radius','qos','policies','logs','alarms','statistics','cpu','memory','disks','filesystems','addresses','routes','neighbors','dns','processes','services','users','groups','ssh','firewall','scheduled-tasks','packages','updates']);
const IMPLEMENTED=new Set(['dashboard','system','health','chassis','boards','cards','ports','pon-ports','uplinks','onus','interfaces','vlans','routing','routes','subscribers','radius','alarms','statistics','cpu','memory','disks','filesystems','addresses','neighbors','dns','ports','processes','services','users','groups','packages','updates','policies','vpn','terminal','backup','configuration','log','logs']);
const getDeviceDefinition=type=>DEVICE_TYPES[type]||null;
const capabilitiesFor=(type,method,firmware='')=>{
  const definition=getDeviceDefinition(type);if(!definition)return[];
  const modules=[...definition.modules,...(definition.modules.includes('backup')?[]:['backup'])];
  return modules.map(name=>({capability:name,supported:IMPLEMENTED.has(name)&&(name!=='terminal'||['ssh','telnet'].includes(method)),readOnly:READ_ONLY.has(name),metadata:{method,firmware,requiresConfirmation:['reboot','shutdown','backup','policies','nat','routing','users','firewall'].includes(name),realDeviceValidationRequired:true}}));
};
module.exports={DEVICE_TYPES,METHODS,STATUSES,getDeviceDefinition,capabilitiesFor};
