const crypto=require('crypto');const {getCapability}=require('./device-capability.registry');const {sanitizeOutput}=require('../device-management/device-connection.service');const {encrypt}=require('../device-management/device-credential.service');const {createAdapter}=require('../device-management/device-adapter.service');
const secretInput=/password|secret|token|community|private.?key/i;
const publicInput=input=>Object.fromEntries(Object.entries(input||{}).map(([key,value])=>[key,secretInput.test(key)?'[removed]':value]));
class DeviceConfigurationTaskService{
 constructor(prisma,connections){this.prisma=prisma;this.connections=connections;}
 async preview(ctx,device,key,input,idempotencyKey){const capability=getCapability(key,device),validated=capability.validate(input||{}),proposedCommands=capability.build(validated),verificationCommands=capability.verify?.(validated)||[],rollbackCommands=capability.rollback?.(validated)||[];let stableKey=String(idempotencyKey||crypto.createHash('sha256').update(`${device.id}:${key}:${JSON.stringify(validated)}`).digest('hex')).slice(0,191),existing=await this.prisma.managedDeviceConfigurationTask.findUnique({where:{ispId_idempotencyKey:{ispId:ctx.ispId,idempotencyKey:stableKey}}});const reusable=existing&&!['FAILED','CANCELLED'].includes(existing.status)&&JSON.stringify(existing.proposedCommands)===JSON.stringify(sanitizeOutput(proposedCommands));if(reusable)return existing;if(existing)stableKey=`${stableKey.slice(0,150)}:${crypto.randomUUID()}`;return this.prisma.managedDeviceConfigurationTask.create({data:{ispId:ctx.ispId,deviceId:device.id,capabilityKey:key,idempotencyKey:stableKey,requestedInput:publicInput(validated),encryptedInput:encrypt(validated),proposedCommands:sanitizeOutput(proposedCommands),verificationCommands,rollbackCommands,riskLevel:capability.riskLevel,status:'WAITING_FOR_APPROVAL',requestedBy:ctx.userId}});}
 async approve(ctx,device,taskId){const task=await this.get(ctx.ispId,device.id,taskId);if(task.status!=='WAITING_FOR_APPROVAL')throw Object.assign(new Error('Only a task waiting for approval can be approved.'),{status:409,code:'TASK_NOT_WAITING'});return this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'APPROVED',approvedBy:ctx.userId,approvedAt:new Date()}});}
 async execute(ctx,device,taskId){const task=await this.get(ctx.ispId,device.id,taskId);if(task.status!=='APPROVED')throw Object.assign(new Error('Configuration task must be approved before execution.'),{status:409,code:'TASK_NOT_APPROVED'});if(process.env.DEVICE_CONFIGURATION_EXECUTION_ENABLED==='false')throw Object.assign(new Error('Live configuration execution was explicitly disabled by the server administrator.'),{status:409,code:'DEVICE_CONFIGURATION_EXECUTION_DISABLED'});let backupRow;try{await this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'BACKING_UP'}});const backup=await createAdapter(device,this.connections).createBackup();backupRow=await this.prisma.managedDeviceBackup.create({data:{deviceId:device.id,name:`pre-change-${task.uuid}`,format:'aes-256-gcm-json',content:encrypt({content:backup.content}),contentHash:backup.hash,sizeBytes:Buffer.byteLength(backup.content),createdBy:ctx.userId}});await this.prisma.managedDevice.update({where:{id:device.id},data:{lastConfigurationBackupId:backupRow.id}});await this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'EXECUTING',backupId:backupRow.id}});const execution=await this.run(device,task.proposedCommands);await this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'VERIFYING',result:sanitizeOutput(execution)}});const verification=await this.run(device,task.verificationCommands);this.verifyTask(task,verification);return this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'COMPLETED',verification:sanitizeOutput(verification),executedAt:new Date()}});}catch(error){await this.prisma.managedDeviceConfigurationTask.update({where:{id:task.id},data:{status:'FAILED',failureReason:String(error.message||error).slice(0,1000)}}).catch(()=>null);throw error;}}
 async run(device,commands){if(!Array.isArray(commands)||!commands.length)return[];return this.connections.withConnection(device,async(connection,method)=>{if(!['SSH','TELNET','ROUTEROS_API','ROUTEROS_API_TLS','ROUTEROS_REST'].includes(String(method).toUpperCase()))throw Object.assign(new Error('Configuration command execution requires SSH, Telnet, or a configured RouterOS API.'),{status:400,code:'CONFIG_PROTOCOL_UNSUPPORTED'});return connection.runShellSession(async send=>{const output=[];const timeout=Math.max(2000,Math.min(Number(device.commandTimeout||15000),20000));for(const command of commands){const response=await send(command,timeout);this.assertCommandSuccess(command,response);output.push({command,output:response});}return output;});});}
 assertCommandSuccess(command,output){const text=String(output||'');if(/(?:%\s*(?:invalid input|incomplete command|ambiguous command|unknown command|error)|command not found|syntax error|permission denied|authorization failed)/i.test(text))throw Object.assign(new Error(`Device rejected command "${command}": ${text.trim().slice(0,500)}`),{status:502,code:'DEVICE_COMMAND_REJECTED'});}
 verifyTask(task,verification){if(!['cisco.createVlan','cisco.renameVlan'].includes(task.capabilityKey))return;const vlanId=Number(task.requestedInput?.vlanId),rows=Array.isArray(verification?.result)?verification.result:[],text=rows.map(row=>String(row?.output||'')).join('\n');if(!vlanId||!new RegExp(`(?:^|\\D)${vlanId}(?:\\D|$)`).test(text))throw Object.assign(new Error(`VLAN ${vlanId} was not present in the post-change device response.`),{status:502,code:'DEVICE_CONFIGURATION_VERIFICATION_FAILED'});}
 async get(ispId,deviceId,id){const task=await this.prisma.managedDeviceConfigurationTask.findFirst({where:{id:Number(id),ispId,deviceId}});if(!task)throw Object.assign(new Error('Configuration task not found.'),{status:404,code:'CONFIGURATION_TASK_NOT_FOUND'});return task;}
 async list(ispId,deviceId){return this.prisma.managedDeviceConfigurationTask.findMany({where:{ispId,deviceId},orderBy:{createdAt:'desc'},take:100});}
}
module.exports=DeviceConfigurationTaskService;
