ALTER TABLE `managed_devices`
  ADD COLUMN `platform` VARCHAR(160) NULL,
  ADD COLUMN `operatingSystem` VARCHAR(160) NULL,
  ADD COLUMN `operatingSystemVersion` VARCHAR(160) NULL,
  ADD COLUMN `serialNumber` VARCHAR(191) NULL,
  ADD COLUMN `sshProfile` VARCHAR(64) NOT NULL DEFAULT 'AUTO',
  ADD COLUMN `legacyCompatibilityEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `lastConnectionError` VARCHAR(1000) NULL,
  ADD COLUMN `lastConnectionDiagnostics` JSON NULL,
  ADD COLUMN `lastConfigurationBackupId` INTEGER NULL;

ALTER TABLE `managed_device_connections`
  ADD COLUMN `requestId` VARCHAR(64) NULL,
  ADD COLUMN `profile` VARCHAR(64) NULL,
  ADD COLUMN `profilesAttempted` JSON NULL,
  ADD COLUMN `errorCode` VARCHAR(100) NULL,
  ADD COLUMN `errorCategory` VARCHAR(100) NULL,
  ADD COLUMN `algorithmDirection` VARCHAR(40) NULL,
  ADD COLUMN `algorithmType` VARCHAR(40) NULL,
  ADD COLUMN `diagnostics` JSON NULL;

CREATE TABLE `managed_device_configuration_tasks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `ispId` INTEGER NOT NULL,
  `deviceId` INTEGER NOT NULL,
  `capabilityKey` VARCHAR(160) NOT NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `requestedInput` JSON NULL,
  `encryptedInput` LONGTEXT NULL,
  `proposedCommands` JSON NOT NULL,
  `verificationCommands` JSON NULL,
  `rollbackCommands` JSON NULL,
  `riskLevel` VARCHAR(24) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  `approvalId` INTEGER NULL,
  `backupId` INTEGER NULL,
  `requestedBy` INTEGER NULL,
  `approvedBy` INTEGER NULL,
  `result` JSON NULL,
  `verification` JSON NULL,
  `rollbackResult` JSON NULL,
  `failureReason` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `approvedAt` DATETIME(3) NULL,
  `executedAt` DATETIME(3) NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `managed_device_configuration_tasks_uuid_key` (`uuid`),
  UNIQUE INDEX `managed_device_configuration_tasks_ispId_idempotencyKey_key` (`ispId`, `idempotencyKey`),
  INDEX `managed_device_configuration_tasks_deviceId_createdAt_idx` (`deviceId`, `createdAt`),
  INDEX `managed_device_configuration_tasks_ispId_status_idx` (`ispId`, `status`),
  CONSTRAINT `managed_device_configuration_tasks_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
