SET @schema_name = DATABASE();

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'intUpload'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `intUpload` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'firDownload'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `firDownload` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'localUpload'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `localUpload` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'localDownload'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `localDownload` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'nasType'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `nasType` VARCHAR(191) NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'service'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `service` VARCHAR(191) NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'priority'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `priority` VARCHAR(191) NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'vendorProfiles'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `vendorProfiles` JSON NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'packageType'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `packageType` VARCHAR(191) NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'allowRename'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `allowRename` BOOLEAN NOT NULL DEFAULT false'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'fupApply'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `fupApply` BOOLEAN NOT NULL DEFAULT true'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'isFupPackage'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `isFupPackage` BOOLEAN NOT NULL DEFAULT false'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'onlyRenewal'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `onlyRenewal` BOOLEAN NOT NULL DEFAULT false'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'applyFramedPool'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `applyFramedPool` BOOLEAN NOT NULL DEFAULT false'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'framedPoolValue'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `framedPoolValue` VARCHAR(191) NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'customRadiusAttributes'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `customRadiusAttributes` JSON NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'maxDiscountPercentage'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `maxDiscountPercentage` DOUBLE NULL DEFAULT 100'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'maxDiscountCount'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `maxDiscountCount` INTEGER NULL DEFAULT 0'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'highPriority'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `highPriority` BOOLEAN NOT NULL DEFAULT false'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
