CREATE TABLE `managed_devices` (
  `id` INTEGER NOT NULL AUTO_INCREMENT, `uuid` VARCHAR(36) NOT NULL, `ispId` INTEGER NOT NULL, `branchId` INTEGER NULL,
  `name` VARCHAR(160) NOT NULL, `slug` VARCHAR(191) NOT NULL, `deviceType` VARCHAR(64) NOT NULL, `vendor` VARCHAR(100) NOT NULL,
  `model` VARCHAR(160) NULL, `firmwareVersion` VARCHAR(160) NULL, `host` VARCHAR(255) NOT NULL, `endpointKey` VARCHAR(64) NOT NULL, `managementPort` INTEGER NOT NULL,
  `communicationMethod` VARCHAR(24) NOT NULL, `defaultCommunicationMethod` VARCHAR(24) NOT NULL, `apiBaseUrl` VARCHAR(500) NULL, `apiPort` INTEGER NULL,
  `tlsEnabled` BOOLEAN NOT NULL DEFAULT false, `verifyTls` BOOLEAN NOT NULL DEFAULT true, `site` VARCHAR(160) NULL, `location` VARCHAR(255) NULL,
  `description` TEXT NULL, `tags` JSON NULL, `status` VARCHAR(24) NOT NULL DEFAULT 'offline', `statusMessage` VARCHAR(1000) NULL,
  `failureReason` VARCHAR(1000) NULL, `maintenanceReason` VARCHAR(1000) NULL, `maintenanceStartedAt` DATETIME(3) NULL,
  `lastCheckedAt` DATETIME(3) NULL, `lastSeenAt` DATETIME(3) NULL, `lastSuccessfulConnectionAt` DATETIME(3) NULL, `lastFailureAt` DATETIME(3) NULL,
  `consecutiveFailureCount` INTEGER NOT NULL DEFAULT 0, `pollingEnabled` BOOLEAN NOT NULL DEFAULT true, `pollingInterval` INTEGER NOT NULL DEFAULT 300,
  `connectionTimeout` INTEGER NOT NULL DEFAULT 15000, `commandTimeout` INTEGER NOT NULL DEFAULT 15000, `retryCount` INTEGER NOT NULL DEFAULT 1,
  `enabled` BOOLEAN NOT NULL DEFAULT true, `isDeleted` BOOLEAN NOT NULL DEFAULT false, `createdBy` INTEGER NULL, `updatedBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `managed_devices_uuid_key`(`uuid`), UNIQUE INDEX `managed_devices_ispId_slug_key`(`ispId`,`slug`),
  UNIQUE INDEX `managed_devices_ispId_deviceType_endpointKey_key`(`ispId`,`deviceType`,`endpointKey`),
  INDEX `managed_devices_ispId_deviceType_isDeleted_idx`(`ispId`,`deviceType`,`isDeleted`), INDEX `managed_devices_ispId_status_enabled_pollingEnabled_idx`(`ispId`,`status`,`enabled`,`pollingEnabled`),
  INDEX `managed_devices_branchId_idx`(`branchId`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `managed_device_credentials` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`encryptedPayload` LONGTEXT NOT NULL,`encryptionVersion` INTEGER NOT NULL DEFAULT 1,`credentialKinds` JSON NULL,`lastRotatedAt` DATETIME(3) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`updatedAt` DATETIME(3) NOT NULL,UNIQUE INDEX `managed_device_credentials_deviceId_key`(`deviceId`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_connections` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`userId` INTEGER NULL,`method` VARCHAR(24) NOT NULL,`success` BOOLEAN NOT NULL,`durationMs` INTEGER NULL,`failureType` VARCHAR(64) NULL,`message` VARCHAR(1000) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_connections_deviceId_createdAt_idx`(`deviceId`,`createdAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_status_history` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`status` VARCHAR(24) NOT NULL,`message` VARCHAR(1000) NULL,`latencyMs` INTEGER NULL,`checkedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_status_history_deviceId_checkedAt_idx`(`deviceId`,`checkedAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_snapshots` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`module` VARCHAR(100) NOT NULL,`reason` VARCHAR(255) NULL,`content` LONGTEXT NOT NULL,`contentHash` VARCHAR(64) NOT NULL,`createdBy` INTEGER NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_snapshots_deviceId_createdAt_idx`(`deviceId`,`createdAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_backups` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`name` VARCHAR(191) NOT NULL,`format` VARCHAR(40) NOT NULL,`content` LONGTEXT NOT NULL,`contentHash` VARCHAR(64) NOT NULL,`sizeBytes` INTEGER NOT NULL,`createdBy` INTEGER NULL,`restoredAt` DATETIME(3) NULL,`restoredBy` INTEGER NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_backups_deviceId_createdAt_idx`(`deviceId`,`createdAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_audits` (`id` INTEGER NOT NULL AUTO_INCREMENT,`ispId` INTEGER NOT NULL,`deviceId` INTEGER NOT NULL,`userId` INTEGER NULL,`action` VARCHAR(100) NOT NULL,`module` VARCHAR(100) NULL,`success` BOOLEAN NOT NULL,`requestSummary` JSON NULL,`responseSummary` JSON NULL,`sourceIp` VARCHAR(64) NULL,`failureReason` VARCHAR(1000) NULL,`beforeData` JSON NULL,`afterData` JSON NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_audits_ispId_createdAt_idx`(`ispId`,`createdAt`),INDEX `managed_device_audits_deviceId_createdAt_idx`(`deviceId`,`createdAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_commands` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`userId` INTEGER NULL,`module` VARCHAR(100) NULL,`command` TEXT NOT NULL,`commandType` VARCHAR(24) NOT NULL,`success` BOOLEAN NOT NULL,`output` LONGTEXT NULL,`failureReason` VARCHAR(1000) NULL,`durationMs` INTEGER NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `managed_device_commands_deviceId_createdAt_idx`(`deviceId`,`createdAt`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `managed_device_capabilities` (`id` INTEGER NOT NULL AUTO_INCREMENT,`deviceId` INTEGER NOT NULL,`capability` VARCHAR(120) NOT NULL,`supported` BOOLEAN NOT NULL DEFAULT true,`readOnly` BOOLEAN NOT NULL DEFAULT false,`metadata` JSON NULL,`detectedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE INDEX `managed_device_capabilities_deviceId_capability_key`(`deviceId`,`capability`),INDEX `managed_device_capabilities_deviceId_supported_idx`(`deviceId`,`supported`),PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `managed_devices` ADD CONSTRAINT `managed_devices_ispId_fkey` FOREIGN KEY (`ispId`) REFERENCES `ISP`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_devices` ADD CONSTRAINT `managed_devices_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `managed_device_credentials` ADD CONSTRAINT `managed_device_credentials_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_connections` ADD CONSTRAINT `managed_device_connections_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_status_history` ADD CONSTRAINT `managed_device_status_history_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_snapshots` ADD CONSTRAINT `managed_device_snapshots_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_backups` ADD CONSTRAINT `managed_device_backups_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_audits` ADD CONSTRAINT `managed_device_audits_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_commands` ADD CONSTRAINT `managed_device_commands_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `managed_device_capabilities` ADD CONSTRAINT `managed_device_capabilities_deviceId_fkey` FOREIGN KEY (`deviceId`) REFERENCES `managed_devices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
