SET @schema_name = DATABASE();

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'fupLimitGb'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `fupLimitGb` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema_name AND TABLE_NAME = 'PackagePlan' AND COLUMN_NAME = 'fupPenaltyPlanId'),
  'SELECT 1',
  'ALTER TABLE `PackagePlan` ADD COLUMN `fupPenaltyPlanId` INTEGER NULL'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
